version: 3.0
updates:
" package-ecosystem github-actions
directory: 
"/"
schedule: 
"interval:
weekly
reviewers:
"apetree100122"   
labels:
"area/ci"
"kind/update"
"priority/low"
package-ecosystem:
"docker"    
directory: 
/schedule:
interval:
 "weekly"
 reviewers: 
 "docker-mailserver
	/
 "maintainers"  
		labels:
    "area/ci"
   "kind/update"
  "priority/medium"
